- name: Enabling VNET logging with Log Analytics Workspace 
  azure.azcollection.azure_rm_monitordiagnosticsetting:
        name: "{{ diag_name }}"
        cloud_environment: "{{ cloud }}"
        client_id: "{{ client_id }}"
        secret: "{{ secret }}"
        tenant: "{{ tenant }}"
        subscription_id: "{{ subscription }}"
        resource:
          name: "{{ vnet_name }}"
          type: "Microsoft.Network/virtualNetworks"
          resource_group: "{{ resource_group }}"
        log_analytics:
             name: "{{ law_name }}"
             resource_group: "{{ law_resource_group }}"
        logs:
            - category_group: "allLogs"
        metrics:
            - category: "AllMetrics"
  register: law_status
#When the Diagnostic is enabled or passed Events
- name: Successful run
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ law_status.state }}"
      status: completed
  when: law_status.failed == false
#Some information not provided and failed event:
- name: For Authentication/Authorization Error
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ law_status.msg }}"
      status: error
  when: 
     - law_status.failed == true
     - law_status.msg is defined