---
- name: Creating VNET {{ vnet_name }}
  azure_rm_virtualnetwork:
         name: "{{ vnet_name }}"
         resource_group: "{{ resource_group }}"
         address_prefixes: "{{ cidr }}"
         cloud_environment: "{{ cloud }}"
         client_id: "{{ client_id }}"
         secret: "{{ secret }}"
         tenant: "{{ tenant }}"
         subscription_id: "{{ subscription }}"
  register: vnet_info
  ignore_errors: true
- name: Send response to Web API for passed cases
  ansible.builtin.uri:
       url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
       method: POST
       body_format: json
       headers: 
           Content-Type: application/json
           Authorization: Bearer {{ token }}
       body: 
          playbook_result: "{{ vnet_info }}"
          status: completed
  when: vnet_info.failed == false
- name: Send respone to the Web API for failed cases
  ansible.builtin.uri:
       url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
       method: POST
       body_format: json
       headers: 
           Content-Type: application/json
           Authorization: Bearer {{ token }}
       body: 
          playbook_result: "{{ vnet_info.msg }}"
          status: error
  when: vnet_info.failed == true