- name: Enabling VNET logging with Storage Account
  azure.azcollection.azure_rm_monitordiagnosticsetting:
        name: "{{ diag_name }}"
        cloud_environment: "{{ cloud }}"
        client_id: "{{ client_id }}"
        secret: "{{ secret }}"
        tenant: "{{ tenant }}"
        subscription_id: "{{ subscription }}"
        resource:
          name: "{{ vnet_name }}"
          type: "Microsoft.Network/virtualNetworks"
          resource_group: "{{ resource_group }}"
        storage_account:
             name: "{{ storage_name}}"
        logs:
            - category_group: "allLogs"
        metrics:
            - category: "AllMetrics"            
  register: sa_status
  ignore_errors: true
#When the Diagnostic is enabled or passed Events
- name: Successful run
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ sa_status.state }}"
      status: completed
  when: sa_status.failed == false
#Some information not provided and failed event:
- name: For Authentication/Authorization Error
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ sa_status.msg }}"
      status: error
  when: 
     - sa_status.failed == true
     - sa_status.msg is defined