---
- name: Block to fetch the user info with user_ID or UPN
  block:
    - name: Generate Access Tokens
      azure.azcollection.azure_rm_accesstoken_info:
          client_id: "{{ client_id }}"
          secret: "{{ secret }}"
          tenant: "{{ tenant }}"
          subscription_id: "{{ subscription }}"
          scopes:
          - https://graph.microsoft.com/.default
      register: azure_token
    - name: Fetch User info
      ansible.builtin.uri:
          url: https://graph.microsoft.com/v1.0/users/{{ user }}
          method: GET
          headers: 
              Content-Type: application/json
              Authorization: Bearer {{ azure_token.access_token }}
      register: user_info
  rescue:
     - name: Authentication or Authorization Error
       set_fact:
           error: "{{ ansible_failed_result.module_stderr.split('\nazure.core.exceptions.')[1] }}"
       when: 
         - ansible_failed_result.module_stderr is defined
         - ansible_failed_result.module_stderr.split('\nazure.core.exceptions.') is defined
     - name: Resource Not Found Error
       set_fact:
          error: "{{ ansible_failed_result.msg }}"
       when: 
         - ansible_failed_result.module_stderr is undefined
         - 
     - name: Other General Error
       set_fact:
           error: "{{ ansible_failed_result.msg }}"
       when: 
         - ansible_failed_result.module_stderr is defined
         - ansible_failed_result.module_stderr.split('\nazure.core.exceptions.') is undefined