---
- name: Deleting Route Table "{{ rt_name }}"
  azure_rm_routetable: 
          name: "{{ rt_name }}"
          resource_group: "{{ resource_group }}"
          state: absent
          client_id: "{{ client_id }}"
          secret: "{{ secret }}"
          tenant: "{{ tenant }}"
          subscription_id: "{{ subscription }}"
  register: rt_del
  ignore_errors: true

- name: Successful run
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ rt_del.id }}"
      status: completed
  when: rt_del.failed == false
#Some information not provided and failed event:
- name: For Overlapping Subnets Error
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ rt_del.msg }}"
      status: error
  when: 
     - rt_del.failed == true
     - rt_del.msg is defined
     - rt_del.module_stderr is undefined
# Authentication & Authorization Traceback
- name: For Authentication/Authorization Error
  ansible.builtin.uri:
    url: http://localhost/microservice/ansible/incident/playbook/result_update?incident_id={{ incident_id }}
    method: POST
    body_format: json
    headers: 
        Content-Type: application/json
        Authorization: Bearer {{ token }}
    body: 
      playbook_result: "{{ rt_del.module_stderr.split('\nazure.core.exceptions.')[1] }}"
      status: error
  when: 
     - rt_del.failed == true
     - rt_del.module_stderr is defined